title: Phao Chanthin
description: >-
  Data Scientist • Data Engineer • Mathematician
  Passionate about solving real-world problems using data.
theme: jekyll-theme-minimal
logo: /profile.jpg
show_downloads: false
